### ISSUE TITLE
スケールのアニメーション

### ISSUE THREAD

**Issue by mkkkk0899** [tkystar/DigitalNature#14]

**Comment by tkystar** [comment]
DoTweenを導入
https://assetstore.unity.com/packages/tools/animation/dotween-hotween-v2-27676?locale=ja-JP

**Comment by tkystar** [comment]
`private void PlayScaleAnimation(GameObject scaledObj)
    {
        Vector3 originalScale = scaledObj.transform.localScale;
        scaledObj.transform.localScale = Vector3.zero;
        scaledObj.transform.DOScale(originalScale, 1f).SetEase(Ease.InCubic);
    }`

**Comment by tkystar** [comment]
生成時にタイムラグがあり、「あれ？」となるのでエフェクトで誤魔化す
https://assetstore.unity.com/packages/vfx/particles/cartoon-fx-free-pack-169179

**Comment by tkystar** [comment]
![Image](https://user-images.githubusercontent.com/71160720/225005568-12ec9661-b028-468c-8580-347a1f86bf30.png)
